services:
  - type: web
    name: phasal-crop-care
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false # User will input this variable manually in the dashboard
      - key: PYTHON_VERSION
        value: 3.11.9
